#!/usr/bin/env python
#
# Copyright 2013 Mawuli Adzaku <mawuli@mawuli.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#	 http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Zotonic CLI for managing modules. Modules are by default pulled from modules.zotonic.com
#

# version

__version__ = "0.1.0"

import os
import sys
import httplib
import re
from urlparse import urlparse

try:
    import json
except ImportError:
    import simplejson as json

INSTALL_PATH = os.path.join(os.environ['ZOTONIC'], 'priv/modules')
BASE_MODULE_PATH = os.path.join(os.environ['ZOTONIC'], 'modules')

# print "Hello, World!"

class ZMM():
    """
    Class for holding all Zotonic module related functions
    """
    # How long should ZMM  run if there's a problem such as  poor internet connection.
    timeout = 60

    def __init__(self):
        pass

    def help(self):
        pass

    def install(self):
        pass

    def uninstall(self):
        pass
   
    def activate(self):
        pass

    def deactivate(self):
        pass

    def freeze(self):
        pass

    def bundle(self):
        pass

    def info(self):
        pass

    def search(self):
        pass

    def update(self):
        pass

    def list(self):
        pass

    def tests(self):
        pass
